
spring:
  application:
    name: user-module
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        register: false # 客户端，无需注册到Zookeeper服务器上
        enabled: true
#        instance-id: 1
#        root: /zk-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moviedb
    username: root
    password: 20031230

mybatis:
  mapperLocations: classpath:mapper/*.xml