#server:
#  port: 8002
spring:
  application:
    name: movie-recommend-service
  cloud:
    zookeeper:
      connect-string: 192.168.43.158:2181
      discovery:
        register: true
        enabled: true
#        instance-id: 2
        root: /zk-server-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moviedb
    username: root
    password: 20031230

mybatis:
  mapperLocations: classpath:mapper/*.xml

