version: '3.3'

services:
  movie-module:
    image: cloud-movie:1.0
    container_name: movie-container
    ports:
      - "8004:8004"
    volumes:
      - ~/movie-docker:/data/movie
    network_mode: host
    #    networks:
    #      - user-docker_mynetwork
    environment:
      - "SPRING_PROFILES_ACTIVE=pro"
    depends_on:
      - zoo2
      - zkmongo
      - zkredis

  zkmongo:
    image: mongo:3.6.23
    container_name: zkmongo
    ports:
      - "27017:27017"
    volumes:
      - ~/movie-docker/mongo-data/db:/data/db
      - ~/movie-docker/mongo-data/log:/var/log/mongodb
      - ~/movie-docker/mongo-data/config:/etc/mongo
    #    command: mongod --auth
    command: --config /etc/mongo/mongod.conf
    network_mode: host
#    networks:
#      - user-docker_mynetwork

  zoo2:
    image: zookeeper:3.5.5
    restart: always
    hostname: zk
    container_name: zk-container
    network_mode: host
    ports:
      - 2181:2181
    volumes:
      - ~/zookeeper/conf:/conf
      - ~/Documents/zk3/data:/data
      - ~/Documents/zk3/logs:/datalog


  zkredis:
    image: redis:6.2.6
    container_name: zkredis2
    ports:
      - "6379:6379"
    volumes:
      - ~/redis/redis.conf:/etc/redis/redis.conf
      - ~/redis/data:/data
    command: redis-server /etc/redis/redis.conf
    network_mode: host
    depends_on:
      - zoo2

#networks:
#  user-docker_mynetwork:
#    external: true