version: '3.3'

services:
  user-module:
    image: cloud-user:1.0
    container_name: user-module-container2
    ports:
      - "8003:8003"
    volumes:
      - ~/user-docker:/data
    network_mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=pro"
    depends_on:
      - zkredis
      - zkmysql
      - zoo1

  zoo1:
    image: zookeeper:3.5.5
    restart: always
    hostname: zk
    container_name: zk-container
    network_mode: host
    ports:
      - 2181:2181
    volumes:
      - ~/zookeeper/conf:/conf
      - ~/Documents/zk2/data:/data
      - ~/Documents/zk2/logs:/datalog

  zkredis:
    image: redis:6.2.6
    container_name: zkredis2
    ports:
      - "6379:6379"
    volumes:
      - ~/redis/redis.conf:/etc/redis/redis.conf
      - ~/redis/data:/data
    command: redis-server /etc/redis/redis.conf
    network_mode: host
    depends_on:
      - zoo1
  #    command: >
  #      apt-get update
  #              && apt-get install net-tool"

  zkmysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    container_name: zkmysql2
    environment:
      MYSQL_ROOT_PASSWORD: "20031230"
      MYSQL_DATABASE: "moviedb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "20031230"
    volumes:
      - ~/mysql/conf/my.cnf:/etc/mysql.cnf
      - ~/mysql/log:/var/log/mysql
      - ~/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    network_mode: host
    depends_on:
      - zoo1


#networks://固定ip
#  mynetwork:
#    ipam:
#      config:
#        - subnet: 172.19.0.0/16
